import { Sour_Gummy, Rock_Salt, Honk} from "next/font/google";
import "./globals.css";

const sour_gummy = Sour_Gummy({
  subsets: ["latin"]
})

export const rock_salt = Rock_Salt({
  weight: '400'
})

const honk = Honk({
  variable: '--font-honk'
})

export const metadata = {
  title: "Quote app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          height: '100vh'
        }}
        className={`antialiased bg-red-400 text-amber-50 ${sour_gummy.className} ${honk.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
